version: "3.8"

services:
  backup:
    image: pigeon-volume-backup:1.0
    build: ./image
    environment:
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - openldap_cfg:/backup/openldap_cfg:ro
      - openldap_db:/backup/openldap_db:ro
      - portainer_data:/backup/portainer_data:ro
      - nexus_data:/backup/nexus_data:ro
      - jenkins_home:/backup/jenkins_home:ro
      - postgres_home:/backup/postgres_home:ro
      - postgres_data:/backup/postgres_data:ro
      - sonarqube_data:/backup/sonarqube_data:ro
      - sonarqube_extensions:/backup/sonarqube_extensions:ro
      - sonarqube_logs:/backup/sonarqube_logs:ro
      - sonarqube_conf:/backup/sonarqube_conf:ro

volumes:
  openldap_cfg:
    name: openldap_cfg
    external: true
  openldap_db:
    name: openldap_db
    external: true
  portainer_data:
    name: portainer_data
    external: true
  nexus_data:
    name: nexus_data
    external: true
  jenkins_home:
    name: jenkins_home
    external: true
  postgres_home:
    name: postgres_home
    external: true
  postgres_data:
    name: postgres_data
    external: true
  sonarqube_data:
    name: sonarqube_data
    external: true
  sonarqube_extensions:
    name: sonarqube_extensions
    external: true
  sonarqube_logs:
    name: sonarqube_logs
    external: true
  sonarqube_conf:
    name: sonarqube_conf
    external: true